name: CI Pipeline

on:
  push:  # Запуск на push
    branches:
      - main
  workflow_dispatch:  # Можливість запуску вручну

jobs:
  build:
    runs-on: ubuntu-latest  # Використання операційної системи Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Клонування репозиторію

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11  # Установити Java 11
          distribution: 'adopt'

      - name: Install dependencies
        run: mvn install  # Завантаження залежностей

      - name: Build project
        run: mvn package  # Створення збірки проекту

      - name: Run tests
        run: mvn test  # Запуск тестів
